import { assert } from "@std/assert";

export function assertReleaseReadmeOmitsWorkbenchStatusLanguage(readme: string) {
  const normalized = readme.toLowerCase();
  for (
    const snippet of [
      "review_status",
      "review",
      "review status note:",
      "review items by",
      "review debt by",
      "unresolved",
      "unresolved workbench state:",
      "deferred",
      "blocked",
      "open review",
      "top unresolved",
      "conflict",
      "conflicts",
      "ambiguity",
      "ambiguous",
      "human review",
      "human decision",
      "decide",
      "decision",
      "readiness",
      "usable-with-warnings",
      "warning",
      "warnings",
      "coverage note",
      "unresolved rows",
      "pending",
      "stale review:",
      "blocked by source:",
      "candidate.",
      "relationship.",
      "legal.",
      "blocked and stale counts report unresolved work",
      "stay review-first",
      "internal",
      "caveat",
      "gap",
      "incomplete",
      "does not claim complete",
      "current-schema",
      "current schema",
      "current db",
      "preexisting db",
      "existing current db",
      "make a new one",
      "create and refetch",
      "schema contract",
      "scratch state",
      "local db",
      "local database",
      "contract",
      "workbench",
      "legacy",
      "migration",
      "migrations",
      "db migration",
      "db migrations",
      "database migration",
      "database migrations",
      "schema_migrations",
      "v2",
    ]
  ) {
    assert(!normalized.includes(snippet), `README should not include ${snippet}`);
  }
}
